//
//  CategoryInteractor.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryBusinessLogic: AnyObject {
    func getCategories(request: CategoryModel.Request)
}

class CategoryInteractor {
    var presenter: CategoryPresentationLogic?
    private var worker: CategoryWorker?
    
}

extension CategoryInteractor: CategoryBusinessLogic {
    
    //request parameter should be removed
    func getCategories(request: CategoryModel.Request) {
        worker = CategoryWorker()
        
        worker?.getCategories(success: { categories in
            
            let response = CategoryModel.Response(categories: categories)
            self.presenter?.presentCategories(response: response)
        }, fail: { message in
            self.presenter?.didFailPresentCategories(error: message)
        })
    }
    
}
