//
//  CategoryRouter.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryRoutingLogic {
    func routeToWorkouts(id: Int, name: String)
}

class CategoryRouter {
    weak var viewController: UIViewController?
    
}


extension CategoryRouter: CategoryRoutingLogic {
    
    func routeToWorkouts(id: Int, name: String) {
        if let workoutsVC = UIStoryboard(name: Ids.VC.workouts, bundle: nil).instantiateViewController(withIdentifier: Ids.VC.workouts) as? WorkoutsViewController {
            workoutsVC.categoryId = id
            workoutsVC.title = name
            WorkoutsConfigurator.configure(vc: workoutsVC)
            viewController?.navigationController?.pushViewController(workoutsVC, animated: true)
        }               
    }
}
