//
//  CategoryPresenter.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryPresentationLogic {
    func presentCategories(response: CategoryModel.Response)
    func didFailPresentCategories(error: String)
}


class CategoryPresenter {
    weak var viewController: CategoryDisplayLogic?
    
}


extension CategoryPresenter: CategoryPresentationLogic {
    
    func presentCategories(response: CategoryModel.Response) {
        var displayedCategories = [CategoryViewModel]()
        
        response.categories.forEach { category in
            if let id = category.id, let name = category.name {
                displayedCategories.append(CategoryViewModel(id: id, name: name))
            }
        }
        
        let viewModel = CategoryModel.ViewModel(displayedCategories: displayedCategories)
        viewController?.displayCategory(from: viewModel)
    }
    
    func didFailPresentCategories(error: String) {
        viewController?.didFailDisplayCategory(withError: error)
    }
    
}
