//
//  CategoryWorker.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryWorkerProtocol {
    func fetchCategories(completion: @escaping (Result<[Category], FetchingError>) -> Void)
}

class CategoryWorker: CategoryWorkerProtocol {
    
    func fetchCategories(completion: @escaping (Result<[Category], FetchingError>) -> Void) {
        Fetcher.shared.fetchData(with: CategoryUrlBuilder.shared, as: WorkoutData<Category>.self) { result in
            switch result {
            case .success(let categories):
                guard let categories = categories.results else { return }
                completion(.success(categories))
                
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
    
}
