//
//  CategoryWorker.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryWorkerProtocol {
    func getCategories(success: @escaping ([Category]) -> (), fail: @escaping (String) -> ())
}

class CategoryWorker: CategoryWorkerProtocol {
    
    func getCategories(success: @escaping ([Category]) -> (), fail: @escaping (String) -> ()) {
        
        Fetcher.shared.fetchData(with: CategoryUrlBuilder.shared.urlString, as: WorkoutData<Category>.self) { category in
            DispatchQueue.main.async {
                guard let categories = category.results else { return }
                success(categories)
            }
        } fail: { message in
            DispatchQueue.main.async {
                fail(message)
            }
        }
    }

}
