//
//  CategoryModels.swift
//  Workout_App
//
//  Created by Saba Khitaridze on 30.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias CategoryViewModel = CategoryModel.ViewModel.displayedCategory

enum CategoryModel {
    
    struct Request {}
    
    struct Response {
        let categories: [Category]
    }
    
    struct ViewModel {
        
        struct displayedCategory {
            let id: Int
            let name: String
            var image: UIImage {
                if let imagePath = UIImage(named: name)?.resizeImage(targetSize: 400) {
                    return imagePath
                }
                return UIImage()
            }
        }
        
        var displayedCategories: [displayedCategory]
    }
}
